version: "3.3"

services:
  nginx-reverse-proxy:
    restart: always
    image: <IMAGE_NAME>
    ports:
      - "6443:443"
    volumes:
      - ./nginx-reverse-proxy/certs:/etc/nginx/certs
    # For development purposes
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./nginx-reverse-proxy/.env
  node-app:
    restart: always
    image: <IMAGE_NAME>
    ports:
      - "6800:80"